//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crownbet_Databse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CrownbetEntities : DbContext
    {
        public CrownbetEntities()
            : base("name=CrownbetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblCustomer_Bet> tblCustomer_Bet { get; set; }
        public virtual DbSet<tblHorse> tblHorses { get; set; }
        public virtual DbSet<tblRace> tblRaces { get; set; }
        public virtual DbSet<tblRace_Horse> tblRace_Horse { get; set; }
        public virtual DbSet<tblRaceStatu> tblRaceStatus { get; set; }
    
        public virtual ObjectResult<SP_GetCustomerDetails_Result> SP_GetCustomerDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCustomerDetails_Result>("SP_GetCustomerDetails");
        }
    
        public virtual ObjectResult<SP_GetHorseDetails_Result> SP_GetHorseDetails(Nullable<long> raceID)
        {
            var raceIDParameter = raceID.HasValue ?
                new ObjectParameter("RaceID", raceID) :
                new ObjectParameter("RaceID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetHorseDetails_Result>("SP_GetHorseDetails", raceIDParameter);
        }
    
        public virtual ObjectResult<SP_GetRaceDetails_Result> SP_GetRaceDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRaceDetails_Result>("SP_GetRaceDetails");
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_GetTotalBets()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_GetTotalBets");
        }
    }
}
